// search VIP care
// const links = document.querySelectorAll('.hfpxzc')
//
// const linksArr = []
//
// links.forEach((item) => {
//     const label = item.getAttribute('aria-label')
//     const url = item.getAttribute('href')
//     const startWith = label.startsWith('VIPcare')
//
//     if (startWith) {
//        // let letter = `${label} ; ${url}`
//        //  console.log(letter)
//         const item = {
//             'title' : label,
//             'url' : url
//         }
//         linksArr.push(item)
//     }
// })

const resultArr = [
{title: 'Tampa - Waters', url: 'https://www.google.com/maps/place/VIPcare+Tampa+-+…IJfwf4TxPBwogRKU2jeVaD9xg?authuser=0&hl=en&rclk=1'},
{title: 'Tampa - Bearss', url: 'https://www.google.com/maps/place/VIPcare+Tampa+-+…IJW3WEWOfHwogR58bRB7X4U9A?authuser=0&hl=en&rclk=1'},
{title: 'at Physician Partners', url: 'https://www.google.com/maps/place/VIPcare+at+Physi…IJP2lUZQ3FwogRj_IVrImQJSI?authuser=0&hl=en&rclk=1'},
{title: 'Largo', url: 'https://www.google.com/maps/place/VIPcare+Largo/da…IJ2b_i81v7wogRgKGhtoNRK-Q?authuser=0&hl=en&rclk=1'},
{title: 'Pinellas Park', url: 'https://www.google.com/maps/place/VIPcare+Pinellas…IJdUAv5x7jwogR1F8XGVVUZBw?authuser=0&hl=en&rclk=1'},
{title: 'Bradenton', url: 'https://www.google.com/maps/place/VIPcare+Bradento…IJ3SQC0xMVw4gRuCWicJTwD2Q?authuser=0&hl=en&rclk=1'},
{title: 'Lakeland', url: 'https://www.google.com/maps/place/VIPcare+Lakeland…IJY1fZwj4_3YgRNrQWwsXALmM?authuser=0&hl=en&rclk=1'},
{title: 'Holiday', url: 'https://www.google.com/maps/place/VIPcare+Holiday/…IJ2dk6GruNwogRskt9tzJn-CM?authuser=0&hl=en&rclk=1'},
{title: 'Valrico', url: 'https://www.google.com/maps/place/VIPcare+Valrico/…IJtQjKXJPNwogRTbVe369ZKRs?authuser=0&hl=en&rclk=1'},
{title: 'Riverview', url: 'https://www.google.com/maps/place/VIPcare+Rivervie…IJ-Ry25kLRwogR5RNWfuzbTao?authuser=0&hl=en&rclk=1'},
{title: 'Clearwater', url: 'https://www.google.com/maps/place/VIPcare+Clearwat…IJ-ViOU0XxwogR1m6tbFGjHt8?authuser=0&hl=en&rclk=1'},
{title: 'Sarasota - Bee Ridge', url: 'https://www.google.com/maps/place/VIPcare+Sarasota…IJGW4B0dJBw4gRFUuo45g7ngc?authuser=0&hl=en&rclk=1'},
{title: 'Sarasota - Fruitville', url: 'https://www.google.com/maps/place/VIPcare+Sarasota…IJKSlX979Hw4gRqnHCVHH0jfg?authuser=0&hl=en&rclk=1'},
{title: 'Clermont', url: 'https://www.google.com/maps/place/VIPcare+Clermont…IJzTOx5UWP54gR4oZynlFADT8?authuser=0&hl=en&rclk=1'},
{title: 'Venice', url: 'https://www.google.com/maps/place/VIPcare+Venice/d…IJlfbcJ89bw4gRglDBtbkoaaQ?authuser=0&hl=en&rclk=1'},
{title: 'Poinciana', url: 'https://www.google.com/maps/place/VIPcare+Poincian…IJLYpM78yd3YgRkIg0KPtc28o?authuser=0&hl=en&rclk=1'},
{title: 'Ocala - On Top of the World', url: 'https://www.google.com/maps/place/VIPcare+Ocala+-+…IJi2lvcm9_6IgRrWpzanBCj74?authuser=0&hl=en&rclk=1'},
{title: 'North Port', url: 'https://www.google.com/maps/place/VIPcare+North+Po…IJx-h19ZJVw4gRiA4PU3F68p0?authuser=0&hl=en&rclk=1'},
{title: 'Winter Garden Village', url: 'https://www.google.com/maps/place/VIPcare+Winter+G…IJa3TM8FJ_54gRDi0kSDyH-WY?authuser=0&hl=en&rclk=1'},
{title: 'Lakeland Hwy 98', url: 'https://www.google.com/maps/place/VIPcare+Lakeland…IJ_VSnB9ZH3YgRef67jVwKQYU?authuser=0&hl=en&rclk=1'},
{title: 'Winter Garden Plant', url: 'https://www.google.com/maps/place/VIPcare+Winter+G…IJuwVxz2CD54gRSv_ACoeP6Uw?authuser=0&hl=en&rclk=1'},
{title: 'The Villages', url: 'https://www.google.com/maps/place/VIPcare+The+Vill…IJo62w1WfF54gRzPdaHyOOjd0?authuser=0&hl=en&rclk=1'},
{title: 'St. Cloud', url: 'https://www.google.com/maps/place/VIPcare+St.+Clou…IJraE-toSP3YgRQasuVanuEC0?authuser=0&hl=en&rclk=1'},
{title: 'Lake Underhill', url: 'https://www.google.com/maps/place/VIPcare+Lake+Und…IJSes2fkZm54gRVcZQk03oWtk?authuser=0&hl=en&rclk=1'},
{title: 'Brandon', url: 'https://www.google.com/maps/place/VIPcare+Brandon/…IJLTPLAFrTwogRvSNGe-XkW-4?authuser=0&hl=en&rclk=1'},
{title: 'Tavares', url: 'https://www.google.com/maps/place/VIPcare+Tavares/…IJy2CbbTm954gRuQTE_gGBsjc?authuser=0&hl=en&rclk=1'},
{title: 'Lady Lake', url: 'https://www.google.com/maps/place/VIPcare+Lady+Lak…IJxeLfnHrH54gRx9IlJDGFsdU?authuser=0&hl=en&rclk=1'},
{title: 'Sun City Center', url: 'https://www.google.com/maps/place/VIPcare+Sun+City…IJM38C8i0pw4gR0MmAub_qz5A?authuser=0&hl=en&rclk=1'},
{title: 'Zephyrhills', url: 'https://www.google.com/maps/place/VIPcare+Zephyrhi…IJW7jgDd5N3YgRF1aaaQDmw40?authuser=0&hl=en&rclk=1'},
{title: 'Belleview', url: 'https://www.google.com/maps/place/VIPcare+Bellevie…IJpfjZA9rR54gR9J22T177DvQ?authuser=0&hl=en&rclk=1'},
{title: 'VIPcare', url: 'https://www.google.com/maps/place/VIPcare/data=!4m…IJuc93MJnU54gRgExPlk_zni8?authuser=0&hl=en&rclk=1'},
{title: 'Port Richey', url: 'https://www.google.com/maps/place/VIPcare+Port+Ric…IJaRIkjG2RwogRg7lS0vNKoEA?authuser=0&hl=en&rclk=1'},
{title: 'Ocala - 60th', url: 'https://www.google.com/maps/place/VIPcare+Ocala+-+…IJjZTwc2J_6IgRkC_lj5Hl2fI?authuser=0&hl=en&rclk=1'},
{title: 'Ocala - 49th', url: 'https://www.google.com/maps/place/VIPcare+Ocala+-+…IJDW5wBUUr5ogRdJuC9CHR9h4?authuser=0&hl=en&rclk=1'},
{title: 'Dade City', url: 'https://www.google.com/maps/place/VIPcare+Dade+Cit…IJ08cY31hT3YgR-gwEIDzxQdQ?authuser=0&hl=en&rclk=1'},
{title: 'Spanish Plaines', url: 'https://www.google.com/maps/place/VIPcare+Spanish+…IJfV8AAZDF54gRYG1iDOkodOI?authuser=0&hl=en&rclk=1'},
{title: 'Ocala - SR 40', url: 'https://www.google.com/maps/place/VIPcare+Ocala+-+…IJgyu73H4t5ogRlSn_TQair0Y?authuser=0&hl=en&rclk=1'},
{title: 'Cape Coral', url: 'https://www.google.com/maps/place/VIPcare+Cape+Cor…IJlf6a1DRB24gRP4j8T671KJ4?authuser=0&hl=en&rclk=1'},
{title: 'Davenport', url: 'https://www.google.com/maps/place/VIPcare+Davenpor…IJ6--McAdx3YgR7yzWhdRlQMw?authuser=0&hl=en&rclk=1'},
{title: 'Ocala - SR 200', url: 'https://www.google.com/maps/place/VIPcare+Ocala+-+…IJcy7ro47V54gR3Ciw5ImInLM?authuser=0&hl=en&rclk=1'},
{title: 'Leesburg', url: 'https://www.google.com/maps/place/VIPcare+Leesburg…IJ9bWZLgHA54gRolirzguldbY?authuser=0&hl=en&rclk=1'},
{title: 'Sarasota – Tamiami', url: 'https://www.google.com/maps/place/VIPcare+Sarasota…IJ7ZKZpGZDw4gRemHguKbA06Q?authuser=0&hl=en&rclk=1'},
{title: 'Cocoa', url: 'https://www.google.com/maps/place/VIPcare+Cocoa/da…IJQwf797-s4IgRJpzVKDvh9Lc?authuser=0&hl=en&rclk=1'},
{title: 'Ocala - Canopy Oaks', url: 'https://www.google.com/maps/place/VIPcare+Ocala+-+…IJI2GeFr_R54gRehRRVQM6SrQ?authuser=0&hl=en&rclk=1'},
{title: 'Fort Myers - Medical Lane', url: 'https://www.google.com/maps/place/VIPcare+Fort+Mye…IJv6bpuXpB24gRfqcdgqL9vmg?authuser=0&hl=en&rclk=1'},
{title: 'Mount Dora', url: 'https://www.google.com/maps/place/VIPcare+Mount+Do…IJ9Y43ULWj54gRaOiSYAcDFUE?authuser=0&hl=en&rclk=1'},
{title: 'Wildwood', url: 'https://www.google.com/maps/place/VIPcare+Wildwood…IJZ6_dvL3D54gRyhX5C1yDAug?authuser=0&hl=en&rclk=1'},
{title: 'Leesburg - Lake', url: 'https://www.google.com/maps/place/VIPcare+Leesburg…IJcyirIgO_54gRuQxR9t7qOmw?authuser=0&hl=en&rclk=1'},
{title: 'Ocoee', url: 'https://www.google.com/maps/place/VIPcare+Ocoee/da…IJ5Vs92hKD54gRZZPKL1zH-60?authuser=0&hl=en&rclk=1'},
{title: 'Dental Tampa', url: 'https://www.google.com/maps/place/VIPcare+Dental+T…IJwUJ_8k_HwogRLv5o1FT2HcA?authuser=0&hl=en&rclk=1'},
{title: 'Ocala - Palms Medical Park', url: 'https://www.google.com/maps/place/VIPcare+Ocala+-+…IJTT0cr13V54gRGNPkkvWyszs?authuser=0&hl=en&rclk=1'},
{title: 'Ormond Beach', url: 'https://www.google.com/maps/place/VIPcare+Ormond+B…IJbVqYspbd5ogRAvVtoUeSgbo?authuser=0&hl=en&rclk=1'},
{title: 'Fort Myers - Metropolis', url: 'https://www.google.com/maps/place/VIPcare+Fort+Mye…IJO1aN82gV24gRJgx7CenZNOA?authuser=0&hl=en&rclk=1'},
{title: 'Estero', url: 'https://www.google.com/maps/place/VIPcare+Estero/d…IJqeCAXRQX24gRCTbcJMHu_50?authuser=0&hl=en&rclk=1'},
{title: 'Port Orange', url: 'https://www.google.com/maps/place/VIPcare+Port+Ora…IJH5iA2lDZ5ogRiTsGZm3-WG8?authuser=0&hl=en&rclk=1'},
{title: 'Apopka', url: 'https://www.google.com/maps/place/VIPcare+Apopka/d…IJyzAoAM1354gRFjqO8vUv7o8?authuser=0&hl=en&rclk=1'},
{title: 'Bonita Springs', url: 'https://www.google.com/maps/place/VIPcare+Bonita+S…IJNeUr5R0Z24gRbXH89InKPEA?authuser=0&hl=en&rclk=1'},
{title: 'West Marion', url: 'https://www.google.com/maps/place/VIPcare+West+Mar…IJp5GIN5zV54gRfNBsr46y1yM?authuser=0&hl=en&rclk=1'},
{title: 'Punta Gorda', url: 'https://www.google.com/maps/place/VIPcare+Punta+Go…IJF8eNSB5Z24gRTlu-ZSakvTA?authuser=0&hl=en&rclk=1'},
{title: 'Ocala 40th', url: 'https://www.google.com/maps/place/VIPcare+Ocala+40…IJE3D1IWUt5ogRiCYIYumQIpE?authuser=0&hl=en&rclk=1'},
{title: 'Ocala - OTOTW - Patrycja Garces, DO', url: 'https://www.google.com/maps/place/VIPcare+Ocala+-+…IJ-a09qpN_6IgROVUXrsdByyY?authuser=0&hl=en&rclk=1'},
{title: 'Fort McCoy', url: 'https://www.google.com/maps/place/VIPcare+Fort+McC…IJD8p3sVE75ogRvP-mRkmIUFU?authuser=0&hl=en&rclk=1'},
{title: 'SR200 - Lourdes Colon-Cacho, MD', url: 'https://www.google.com/maps/place/VIPcare+SR200+-+…IJfcZ34fTV54gR1KhpLNi8KSY?authuser=0&hl=en&rclk=1'},
{title: 'Merritt Island', url: 'https://www.google.com/maps/place/VIPcare+Merritt+…IJMw6XL62p4IgRjOwP1e6PcFk?authuser=0&hl=en&rclk=1'},
{title: 'Rockledge', url: 'https://www.google.com/maps/place/VIPcare+Rockledg…IJZ9vi6gsB3ogRxeCYjz968bE?authuser=0&hl=en&rclk=1'},
{title: 'Melbourne', url: 'https://www.google.com/maps/place/VIPcare+Melbourn…IJo-oj24AR3ogRAxQ_GbILLkg?authuser=0&hl=en&rclk=1'},
{title: 'OTOTW - Dr. Larry Kettlewell', url: 'https://www.google.com/maps/place/VIPcare+OTOTW+-+…IJMTnv5Ip_6IgR_50n7CVPm68?authuser=0&hl=en&rclk=1'},
{title: 'Orange Park', url: 'https://www.google.com/maps/place/VIPcare+Orange+P…IJ-V3VeFjF5YgROI80HuCrNVM?authuser=0&hl=en&rclk=1'},
{title: 'Jacksonville - Baymeadows', url: 'https://www.google.com/maps/place/VIPcare+Jacksonv…IJj7dikZTL5YgR6eZeES1oTNw?authuser=0&hl=en&rclk=1'},
{title: 'Boynton Beach', url: 'https://www.google.com/maps/place/VIPcare+Boynton+…IJt5dKeRff2IgRaEjKSs-TeRE?authuser=0&hl=en&rclk=1'},
{title: 'Jacksonville - University', url: 'https://www.google.com/maps/place/VIPcare+Jacksonv…IJNT3_LMa15YgRd0SDlzS0-JU?authuser=0&hl=en&rclk=1'},
{title: 'Jacksonville - Gate Parkway', url: 'https://www.google.com/maps/place/VIPcare+Jacksonv…IJY54YkgPL5YgRPpvF84W_rmY?authuser=0&hl=en&rclk=1'},
{title: 'Pensacola - Pine Forest', url: 'https://www.google.com/maps/place/VIPcare+Pensacol…IJ75uoZhO9kIgRljdwU_VYMDw?authuser=0&hl=en&rclk=1'},
{title: 'Pensacola - Davis Hwy', url: 'https://www.google.com/maps/place/VIPcare+Pensacol…IJm_e52mW_kIgRWs3lUzA-prg?authuser=0&hl=en&rclk=1'}
]

const locationsArr = [
    "Huntsville - Hospital Drive",
    "Marietta",
    "Hiram",
    "Greenville",
    "SaludVIP Winter Park",
    "SaludVIP Tampa - Wellswood",
    "SaludVIP Ocala - Southwest",
    "SaludVIP Orlando - MetroWest",
    "SaludVIP Orlando - Hunter's Creek",
    "SaludVIP DeLand",
    "SaludVIP Plant City - Coming Soon!",
    "SaludVIP Sarasota Commons - Coming Soon!",
    "SaludVIP Altamonte Springs - Coming Soon!",
    "SaludVIP Orlando - Conway - Coming Soon!",
    "VIPcare at Centennial Health - Oklahoma City",
    "VIPcare at Centennial Health - Midwest City",
    "VIPcare at Centennial Health - Edmond",
    "VIPcare at Centennial Health - Broken Arrow",
    "Orlando - Metro West - Coming Soon",
    "Estero",
    "Fort Myers - Sanibel Beach Place - Coming soon!",
    "Lake Worth - Coming Soon",
    "Rockledge",
    "Holiday",
    "Bonita Springs",
    "Melbourne",
    "VIPcare at Harvard Family Physicians",
    "Centre",
    "Fairhope",
    "Mobile",
    "Spanish Fort",
    "Foley",
    "SaludVIP Port St Lucie",
    "SaludVIP Ocala - Silver Springs Shores",
    "SaludVIP Fort Pierce - Coral Square",
    "SaludVIP San Antonio - Monticello Park - Coming soon!",
    "SaludVIP San Antonio - South Park Plaza﻿ - Coming Soon!",
    "SaludVIP San Antonio - Northwest - Coming soon!",
    "SaludVIP San Antonio - Questa Loma - Coming Soon!",
    "SaludVIP San Antonio - Austin Heights - Coming soon!",
    "Valrico",
    "Leesburg - Lake",
    "Wildwood",
    "Jacksonville - University",
    "Apopka",
    "Dade City",
    "Lakeland - Hwy 98",
    "Mobile - Skyline - Coming soon!",
    "Jacksonville - Baymeadows",
    "Hurst",
    "Mobile - Midtown - Coming soon!",
    "SaludVIP Deltona",
    "SaludVIP Palm Bay",
    "Clearwater",
    "Zephyrhills",
    "Arlington",
    "Punta Gorda",
    "Orange Park",
    "Ocala - Palms Medical Park",
    "Jacksonville - Gate Parkway",
    "Ocala - West Marion",
    "Ocala - Oakbrook",
    "Fort McCoy",
    "Pensacola - Nine Mile",
    "Riverview",
    "Boynton Beach",
    "Davenport",
    "SaludVIP Oviedo",
    "Ocoee",
    "SaludVIP Four Corners",
    "SaludVIP Marion Oaks",
    "Sarasota - Tamiami",
    "Port Richey",
    "Poinciana",
    "Brandon",
    "Mount Dora",
    "Pinellas Park",
    "Largo",
    "Tampa - Waters",
    "Fort Myers - Metropolis",
    "Ocala - SR 40",
    "Ormond Beach",
    "Ocala - 49th",
    "Cape Coral",
    "Merritt Island",
    "Pensacola - Pine Forest",
    "Winter Garden - Winter Garden Village",
    "Sarasota - Fruitville",
    "Spanish Plaines",
    "Fort Myers - Medical Lane",
    "Pensacola - Davis Hwy",
    "SaludVIP St. Cloud",
    "SaludVIP Winter Haven",
    "SaludVIP Kissimmee",
    "SaludVIP Sanford",
    "SaludVIP East Orlando",
    "Lakeland",
    "Ocala - 17th",
    "Pensacola - Mobile Hwy",
    "Bradenton",
    "Sun City Center",
    "Sarasota - Bee Ridge",
    "Port Charlotte",
    "Ocala - SR 200",
    "Milton",
    "Ocala - Canopy Oaks",
    "Lake Underhill",
    "Port Orange",
    "St. Cloud",
    "SaludVIP Clermont",
    "North Port",
    "Venice",
    "Ocala - On Top of the World",
    "Tampa - Bearss",
    "Cocoa",
    "Winter Garden - Plant",
    "Clermont",
    "Tavares",
    "Belleview",
    "Leesburg",
    "The Villages",
    "Lady Lake",
    "Ocala - 60th",
]

resultArr.forEach((item) => {
    const title = item.title
    locationsArr.forEach((location) => {
        if (location.includes(title)) {
            console.log(item.title)
        }
    })
})